name: krafttanken
favicon: null
layout_spectrum: 0.36733
typography_spectrum: 0.84206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfff6'
    - '#070707'
    - '#dd9ab9'
    - '#b2677b'
    - '#64433e'
  brandStrength: 0.6875
  lightness: 0.8424757032189518
  saturation: 0.6135027762502432
  rhythmicContrast: 0.6267114144284278
purpose: []
